//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bibliography
    {
        public int Source_Id { get; set; }
        public string Source_Title { get; set; }
        public string Metric_Name { get; set; }
        public string Agent_Name { get; set; }
        public string Source_Link { get; set; }
        public string Source_Citation { get; set; }
    }
}
