//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bio_Clinical
    {
        public int Host { get; set; }
        public string Generation_Time { get; set; }
        public string Duration_Immunity { get; set; }
        public string CFR { get; set; }
        public string IFR { get; set; }
    }
}
