//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_Geography
    {
        public string Country_Name { get; set; }
        public string Agent { get; set; }
        public int Case_Fatality_Ratio { get; set; }
        public int Contact_Rate { get; set; }
        public int Degree_of_contact { get; set; }
        public int Duration_of_immunity { get; set; }
        public int Environmental_persistance { get; set; }
        public int Vaccine_Treatment { get; set; }
        public int Drug_treatment { get; set; }
        public int Generation_time { get; set; }
        public int History { get; set; }
        public int IFR { get; set; }
        public int Infection_illness_overlap { get; set; }
        public int Number_of_possible_modes { get; set; }
        public int Probability_of_Transmission { get; set; }
        public int Uncertainty_of_Agent_Species { get; set; }
        public int Uncertainty_of_Agent_Relatives { get; set; }
        public int Host_Endemicity { get; set; }
        public int Resevoir_Endemicity { get; set; }
        public int Resevoir_Type { get; set; }
    }
}
