//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHSI
    {
        public int Host { get; set; }
        public string Prevention { get; set; }
        public string Detection { get; set; }
        public string Rapid_Response { get; set; }
        public string Health_System { get; set; }
        public string Compliance { get; set; }
        public string Risk_Environment { get; set; }
    }
}
