//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metric_Sources
    {
        public int Metric_Id { get; set; }
        public string Metric_Name { get; set; }
        public string Metric_Source_Name { get; set; }
        public string Metric_Source_Link { get; set; }
        public string Metric_Citation { get; set; }
        public string Agent_Source_Name { get; set; }
        public string Agent_Source_Link { get; set; }
        public string Agent_Citation { get; set; }
    }
}
