//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Psych
    {
        public int Host { get; set; }
        public string History { get; set; }
        public string Public_Awareness { get; set; }
        public string Symptom_induced_fear { get; set; }
        public string Uncertainty_of_Agent_Species { get; set; }
        public string Uncertainty_of_Agent_Relatives { get; set; }
    }
}
