//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resevoir_Host_Region
    {
        public string Resevoir_Type { get; set; }
        public string Resevoir_Endemicity { get; set; }
        public string Host_Endemicity { get; set; }
        public int Host { get; set; }
    }
}
