//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Survey_History
    {
        public int Compliance { get; set; }
        public int Resevoir_Type { get; set; }
        public int Resevoir_Endemicity { get; set; }
        public int Host_Endemicity { get; set; }
        public int Degree_of_contact { get; set; }
        public int Number_of_possible_modes { get; set; }
        public int Environmental_persistance { get; set; }
        public int Infection_illness_overlap { get; set; }
        public int Drug_treatment { get; set; }
        public int Vaccine_Treatment { get; set; }
        public int Generation_time { get; set; }
        public int Duration_of_immunity { get; set; }
        public int CFR { get; set; }
        public int IFR { get; set; }
        public int History { get; set; }
        public int Public_Awareness { get; set; }
        public int Symptom_induced_fear { get; set; }
        public int Uncertainty_of_Agent_Species { get; set; }
        public int Uncertainty_of_Agent_Relatives { get; set; }
        public int Detection { get; set; }
        public int System { get; set; }
        public int Environment { get; set; }
        public int prevention { get; set; }
        public int response { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> C_Date { get; set; }
    }
}
