//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Testing_Pathogens
    {
        public string Agent_Name { get; set; }
        public int Resevoir_Type { get; set; }
        public Nullable<int> Resevoir_Endemicity { get; set; }
        public Nullable<int> Host_Endemicity { get; set; }
        public Nullable<int> Contact_Rate { get; set; }
        public Nullable<int> Probability_of_Transmission { get; set; }
        public Nullable<int> Degree_of_contact { get; set; }
        public int Number_of_possible_modes { get; set; }
        public Nullable<int> Environmental_persistance { get; set; }
        public Nullable<int> Infection_illness_overlap { get; set; }
        public Nullable<int> Drug_treatment { get; set; }
        public Nullable<int> Vaccine_Treatment { get; set; }
        public int Generation_time { get; set; }
        public Nullable<int> Duration_of_immunity { get; set; }
        public Nullable<int> CFR { get; set; }
        public Nullable<int> IFR { get; set; }
        public Nullable<int> History { get; set; }
        public Nullable<int> Public_Awareness { get; set; }
        public Nullable<int> Symptom_induced_fear { get; set; }
        public Nullable<int> Uncertainty_of_Agent_Species { get; set; }
        public Nullable<int> Uncertainty_of_Agent_Relatives { get; set; }
    }
}
