//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication4
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transmission
    {
        public int Host { get; set; }
        public string Degree_of_Contact { get; set; }
        public string Number_of_possible_modes { get; set; }
        public string Environmental_Persistence { get; set; }
        public string Infectivity_Overlap { get; set; }
    }
}
